// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urlouivlrywooloecljr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVybG91aXZscnl3b29sb2VjbGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjY2NjMsImV4cCI6MjA1OTYwMjY2M30.QCPpKxn4IoUpDLD3gibxkhtRuEPca9vNhEh-zS-QWd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);